# Generated by Django 4.2.4 on 2023-08-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('description', models.CharField(max_length=130)),
                ('host', models.CharField(max_length=130)),
                ('port', models.CharField(max_length=130)),
                ('user', models.CharField(max_length=130)),
                ('password', models.CharField(max_length=130)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
