# Generated by Django 4.2.4 on 2023-08-27 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('searchbackend', '0001_initial'),
        ('storagebackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('description', models.CharField(max_length=130)),
                ('storagebackend_user', models.CharField(max_length=130)),
                ('storagebackend_password', models.CharField(max_length=130)),
                ('active', models.BooleanField(default=False)),
                ('searchbackend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchbackend.searchbackend')),
                ('storagebackend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storagebackend.storagebackend')),
            ],
        ),
    ]
