# Generated by Django 4.2.4 on 2023-08-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('description', models.CharField(max_length=130)),
                ('kind', models.CharField(choices=[('s3', 's3'), ('sftp', 'sftp')], max_length=130)),
                ('url', models.CharField(max_length=130)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
